### ============================================================================
### [02_set_stat_model] accessors and methods for RflomicsMAE and RflomicsSE classes
### ----------------------------------------------------------------------------
# D. Charif,
# C. Payasant-Le-roux, 
# N. Bessoltane

#' @importFrom magrittr "%>%" 
NULL

# ---- generateModelFormulae ----
#' @title Statistical model formulae
#' @name generateModelFormulae
#' @aliases generateModelFormulae,RflomicsMAE-method
#' @rdname generateModelFormulae
#' @description
#' These methods allow the user to select and set the formula of 
#' the statistical method.
#' \itemize{
#'    \item generateModelFormulae():
#'  From a vector of character giving the name of the factors of an omics
#'  experiment, and their type of effect: biological or batch, it returns all 
#'  models formulae that can be formulated in association with this factors. 
#'  Batch effect factors do not appear in interaction terms with biological 
#'  factor. Model formulae stop in second order interaction.}
#' @param object an object of class \link{RflomicsSE} or 
#' class \link{RflomicsMAE-class}
#' @return a named list of object of class formula
#' @exportMethod generateModelFormulae
#' @example inst/examples/statSetting.R
setMethod(f          = "generateModelFormulae",
          signature  = "RflomicsMAE",
          definition = function(object){
            
            return(.generateModelFormulae(getBioFactors(object),
                                          getBatchFactors(object)))
          })

# ---- setModelFormula : ----

#' @name setModelFormula
#' @aliases setModelFormula,RflomicsMAE-method
#' @rdname generateModelFormulae
#' @param object an object of class \link{RflomicsSE} or 
#' class \link{RflomicsMAE-class}
#' @param modelFormula a string of model formula generated by 
#' \link{generateModelFormulae}
#' @return an object of \link{RflomicsSE} class or \link{RflomicsMAE-class}
#'  class
#' @description
#' \itemize{
#'    \item setModelFormula():
#'    Set the model formula stored in \code{metadata} slot}
setMethod(
  f          = "setModelFormula",
  signature  = "RflomicsMAE",
  definition = function(object, modelFormula=NULL){
    
    if(is.null(modelFormula)){
      warning("You forgot to specify 'modelFormula'.")
      return(object)
    } 
    modelFormula <- deparse(as.formula(modelFormula))
    
    # check model formula validity
    possibleFormula <- 
      .generateModelFormulae(getBioFactors(object), getBatchFactors(object))
    
    if(isFALSE(modelFormula %in% sapply(possibleFormula, function(x) deparse(x)))){
      warning("Invalid formula. See generateModelFormulae() 
              for the list of possible formulas.")
      return(object)
    }
      
    metadata(object)$design$Model.formula <- modelFormula
    
    metadata(object)$design$Contrasts.Sel <- 
      generateExpressionContrast(object)
    
    for(name in names(object)){
      # current SE
      designFactors <- getFactorNames(object[[name]])
      modelFormula2 <- 
        .updateModelFormula(
          designFactors, 
          modelFormula = modelFormula
        )
      object[[name]] <- 
        setModelFormula(
          object[[name]], 
          modelFormula = modelFormula2
        )
      
      # raw SE
      designFactors <- 
        getFactorNames(metadata(object[[name]])[["rawRflomicsSE"]])
      modelFormula3 <- 
        .updateModelFormula(
          designFactors, 
          modelFormula = modelFormula
        )
      metadata(object[[name]])[["rawRflomicsSE"]] <-
        setModelFormula(
          metadata(object[[name]])[["rawRflomicsSE"]], 
          modelFormula = modelFormula3
        )
    }
    
    return(object)
  })

#' @name setModelFormula
#' @aliases setModelFormula,RflomicsSE-method
#' @rdname generateModelFormulae
#' @exportMethod setModelFormula
setMethod(f          = "setModelFormula",
          signature  = "RflomicsSE",
          definition = function(object, modelFormula=NULL){
            
            if(is.null(modelFormula)){
              warning("You forgot to specify 'modelFormula'.")
              return(object)
            } 
            
            modelFormula <- deparse(as.formula(modelFormula))
            
            # check model formula validity
            possibleFormula <- 
              .generateModelFormulae(
                getBioFactors(object), 
                getBatchFactors(object)
              )
            
            if(isFALSE(modelFormula %in% sapply(possibleFormula, function(x) deparse(x)))){
              warning("Invalid formula. See generateModelFormulae() 
              for the list of available formulas.")
              return(object)
            }
            
            metadata(object)$design$Model.formula <- modelFormula
            
            metadata(object)$design$Contrasts.Sel <- 
              generateExpressionContrast(object)
            
            return(object)
          })

# ---- getModelFormula : Get Model Formula : ----
#' @rdname generateModelFormulae
#' @name getModelFormula
#' @aliases getModelFormula,RflomicsMAE-method
#' @description
#' \itemize{
#'    \item getModelFormula:
#'  Access to the model formula of the statistical analysis}
#' @exportMethod getModelFormula
setMethod(f          = "getModelFormula",
          signature  = "RflomicsMAE",
          definition = function(object){
            
            Model <- metadata(object)$design$Model.formula
            if(length(Model) == 0) return(NULL)
            
            return(Model)
          })

#' @exportMethod getModelFormula
#' @rdname generateModelFormulae
#' @name getModelFormula
#' @aliases getModelFormula,RflomicsSE-method
setMethod(f          = "getModelFormula",
          signature  = "RflomicsSE",
          definition = function(object){
            
            Model <- metadata(object)$design$Model.formula
            if(length(Model) == 0) return(NULL)
            
            return(Model)
          })


# ---- update modelFormula ----
#' @rdname generateModelFormulae
#' @name updateModelFormula
#' @aliases updateModelFormula,RflomicsMAE-method
#' @description
#' \itemize{
#'    \item Update model formula according to the subset design}
#' @exportMethod updateModelFormula
setMethod(f          = "updateModelFormula",
          signature  = "RflomicsMAE",
          definition = function(object, SE.name = NULL){
            
            updateModelFormula(object[[SE.name]])
          })


#' @rdname generateModelFormulae
#' @name updateModelFormula
#' @aliases updateModelFormula,RflomicsMAE-method
#' @exportMethod updateModelFormula
setMethod(f          = "updateModelFormula",
          signature  = "RflomicsSE",
          definition = function(object){
            
            model_LM      <- getModelFormula(object)
            designFactors <- getFactorNames(object)
            
            model_LM2 <- 
              .updateModelFormula(designFactors, model_LM)
            
            if(deparse(model_LM2) == model_LM)
              return(object)
            # set model and update contrast exps
            setModelFormula(object, modelFormula = model_LM2)
          })

# ---- generateExpressionContrast ----
#' @title Contrast expressions
#' @name generateExpressionContrast
#' @aliases generateExpressionContrast,RflomicsSE-method
#' @rdname generateExpressionContrast
#' @description
#' Generate expression of contrasts based on chosed model formula.
#' \itemize{
#'    \item generateExpressionContrast:
#'  This function allows, from a model formulae, to give the 
#'  expression contrast data frames.
#'  Three types of contrasts are expressed:
#'  \itemize{
#'  \item pairwise comparison 
#'  \item averaged expression 
#'  \item interaction expression 
#' }}
#' @param object an object of class \link{RflomicsSE} or 
#' class \link{RflomicsMAE-class}
#' @param contrastType type of contrasts from which the possible 
#' contrasts are extracted ("average", "simple", "interaction"). 
#' Default is all contrasts types.
#' @exportMethod generateExpressionContrast
#' @author Christine Paysant-Le Roux, adapted by Nadia Bessoltane
#' @example inst/examples/statSetting.R
setMethod(f          = "generateExpressionContrast",
          signature  = "RflomicsSE",
          definition = function(object, 
                                contrastType = NULL){
            
            allcontrast <- 
              .generateExpressionContrast(
                object,
                contrastType = contrastType
              )
            
            #metadata(object)$design$Contrasts.Sel <- allcontrast
            
            return(allcontrast)
          })

#' @rdname generateExpressionContrast
#' @name generateExpressionContrast
#' @aliases generateExpressionContrast,RflomicsMAE-method
#' @exportMethod generateExpressionContrast
setMethod(f          = "generateExpressionContrast",
          signature  = "RflomicsMAE",
          definition = function(object, 
                                contrastType = NULL){
            
            allcontrast <- 
              .generateExpressionContrast(
                object,
                contrastType = contrastType
              )
            
            #metadata(object)$design$Contrasts.Sel <- allcontrast
            
            return(allcontrast)
          })


# ---- setSelectedContrasts ----
#' @rdname generateExpressionContrast
#' @description
#' \itemize{
#'    \item setSelectedContrasts: 
#'  Set the selected contrasts stored in \code{metadata} slot}
#' @param contrastList a data.frame of contrasts generated by 
#' \link{generateExpressionContrast}
#' @return an object of \link{RflomicsSE} class or \link{RflomicsMAE-class}
#'  class
#' @exportMethod setSelectedContrasts
#' @name setSelectedContrasts
#' @aliases setSelectedContrasts,RflomicsMAE-method
setMethod(
  f          = "setSelectedContrasts",
  signature  = "RflomicsMAE",
  definition = function(object, contrastNames=NULL){
    
    if(is.null(contrastNames)){
      warning("You forgot to specify 'contrastNames'.")
      return(object)
    }
    
    all.contrast <- metadata(object)$design$Contrasts.Sel
    
    contrastNames <- 
      intersect(
        all.contrast$contrastName,
        contrastNames
      )
    
    if(is.null(contrastNames)){
      stop("pas d'intersection")
    }
    
    all.contrast[all.contrast$contrastName %in% contrastNames,"selected"] <- 
      "yes"
      
    metadata(object)$design$Contrasts.Sel <- all.contrast
    
    for(name in names(object)){
      #current SE
      metadata(object[[name]])$design$Contrasts.Sel <- all.contrast
      
      #raw SE
      rawRflomicsSE <- metadata(object[[name]])[["rawRflomicsSE"]]
      metadata(rawRflomicsSE)$design$Contrasts.Sel <- all.contrast
      metadata(object[[name]])[["rawRflomicsSE"]] <- rawRflomicsSE
    }
    
    return(object)
  })


#' @rdname generateExpressionContrast
#' @exportMethod setSelectedContrasts
#' @name setSelectedContrasts
#' @aliases setSelectedContrasts,RflomicsSE-method
setMethod(
  f          = "setSelectedContrasts",
  signature  = "RflomicsSE",
  definition = function(object, contrastNames=NULL){
    
    if(is.null(contrastNames)){
      warning("You forgot to specify 'contrastNames'.")
      return(object)
    }
    
    all.contrast <- metadata(object)$design$Contrasts.Sel
    
    contrastNames <- 
      intersect(
        all.contrast$contrastName,
        contrastNames
      )
    
    if(is.null(contrastNames)){
      stop("pas d'intersection")
    }
    
    all.contrast[all.contrast$contrastName %in% contrastNames,"selected"] <- 
      "yes"
    
    metadata(object)$design$Contrasts.Sel <- all.contrast
    
    return(object)
  })


# ---- getSelectedContrasts : ----
#' @rdname generateExpressionContrast
#' @exportMethod getSelectedContrasts
#' @name getSelectedContrasts
#' @param all TRUE: all contrasts; FALSE: user selected contrasts
#' @aliases getSelectedContrasts,RflomicsMAE-method
#' @description
#' \itemize{
#'    \item getSelectedContrasts:
#'  List the selected contrasts}
setMethod(f          = "getSelectedContrasts",
          signature  = "RflomicsMAE",
          definition = function(object, all = FALSE){
            
            contrastList <- metadata(object)$design$Contrasts.Sel
            
            if(!all)
              contrastList <- contrastList[contrastList$selected == "yes",]
              
            return(contrastList)
          })

#' @rdname generateExpressionContrast
#' @exportMethod getSelectedContrasts
#' @name getSelectedContrasts
#' @aliases getSelectedContrasts,RflomicsSE-method
setMethod(f          = "getSelectedContrasts",
          signature  = "RflomicsSE",
          definition = function(object, all = FALSE){
            
            contrastList <- metadata(object)$design$Contrasts.Sel
            
            if(!all)
              contrastList <- contrastList[contrastList$selected == "yes",]
            
            return(contrastList)
          })

# ---- getContrastMatrix ----
# to write